version: "3.9"

services:
  db:
    build: ./database
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet
    restart: always

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    environment:
      DB_HOST: db   
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynet
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge